version: '3.2'

networks:
  app:

services:
  api:
    build: .
    environment:
      - MONGO_HOST=mongo:27017
      - MONGO_NAME=test
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app

  mongo:
    image: 'mongo'
    volumes:
      - type: tmpfs
        target: /data/db
    networks:
      - app

